"""Single writer of provenance/claims.yaml (C4, C5, C7).

Assembles
    thesis + claims   from provenance/claims_statements.yaml; every {{key|format}} in a statement is replaced by
                      format(numbers.json[key].value, format), and the keys are added to the claim's `numbers`
                      (C2: no number is typed by hand). A missing key is an error.
    figures           from every provenance/figures/*.json record written by the fig_*.py scripts
Run: python3 electron_losses_IGM/scripts/build_claims.py
"""

import json
import pathlib
import re

import yaml

ROOT = pathlib.Path(__file__).resolve().parents[2]
STATEMENTS = ROOT / "provenance" / "claims_statements.yaml"
OUT = ROOT / "provenance" / "claims.yaml"
NUMBERS = ROOT / "provenance" / "numbers.json"
PLACEHOLDER = re.compile(r"\{\{([\w.+-]+)\|([^}]*)\}\}")


def render(claim, numbers):
    keys = PLACEHOLDER.findall(claim["statement"])
    missing = [k for k, _ in keys if k not in numbers]
    if missing:
        raise KeyError(f"claim {claim['id']}: keys not in numbers.json: {missing}")
    out = dict(claim)
    out["statement_template"] = claim["statement"]
    out["statement"] = PLACEHOLDER.sub(lambda m: format(numbers[m.group(1)]["value"], m.group(2)), claim["statement"])
    out["numbers"] = list(dict.fromkeys([k for k, _ in keys] + claim.get("numbers", [])))
    return out


def main():
    st = yaml.safe_load(STATEMENTS.read_text(encoding="utf-8")) if STATEMENTS.exists() else {}
    figs = [json.loads(p.read_text(encoding="utf-8")) for p in sorted((ROOT / "provenance" / "figures").glob("*.json"))]
    numbers = json.loads(NUMBERS.read_text(encoding="utf-8")) if NUMBERS.exists() else {}
    doc = {"thesis": st.get("thesis"), "claims": [render(c, numbers) for c in st.get("claims", [])], "figures": figs}
    header = ("# GENERATED by electron_losses_IGM/scripts/build_claims.py — do not edit by hand.\n"
              "# Claims come from provenance/claims_statements.yaml; figures from provenance/figures/*.json.\n")
    OUT.write_text(header + yaml.safe_dump(doc, allow_unicode=True, sort_keys=False, width=120), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}: {len(doc['claims'])} claims, {len(figs)} figures")


if __name__ == "__main__":
    main()
